CREATE TABLE PERSON (
ID INTEGER NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR NOT NULL,
LAST_NAME VARCHAR NOT NULL,
BETREUER_ID INT NOT NULL
);

CREATE TABLE ADDRESS(
PERSON_ID INTEGER NOT NULL PRIMARY KEY,
STREET VARCHAR NOT NULL,
CITY VARCHAR NOT NULL,
ZIP VARCHAR NOT NULL
);

CREATE TABLE BETREUER(
ID INTEGER NOT NULL PRIMARY KEY,
NAME VARCHAR NOT NULL
);

CREATE TABLE TERMIN (
ID INTEGER NOT NULL PRIMARY KEY,
NAME VARCHAR NOT NULL
);

CREATE TABLE USERS (
ID INTEGER NOT NULL PRIMARY KEY,
USERNAME VARCHAR NOT NULL,
PASSWORD VARCHAR NOT NULL,
ROLE INT NOT NULL
);

-- Junction Table for Many-To-Many Relationship
CREATE TABLE PERSON_TERMIN(
TERMIN_ID INTEGER REFERENCES TERMIN (ID) ON UPDATE CASCADE ON DELETE CASCADE,
PERSON_ID INTEGER REFERENCES PERSON (ID) ON UPDATE CASCADE ON DELETE CASCADE,
KEY(TERMIN_ID, PERSON_ID)
);

ALTER TABLE ADDRESS ADD CONSTRAINT FK_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON;
ALTER TABLE PERSON ADD CONSTRAINT FK_BETREUER FOREIGN KEY (BETREUER_ID) REFERENCES BETREUER; 

-- INSERT Statements here
INSERT INTO USERS(ID, USERNAME, PASSWORD, ROLE) VALUES (1, 'admin', 'god', 1);