INSERT INTO ROLE(ID, NAME) VALUES(1, 'ADMIN';)

INSERT INTO USERS(ID, USERNAME, PASSWORD, ROLE) VALUES (1, 'admin', 'god', 1);

INSERT INTO BETREUER(ID, NAME) VALUES (1, 'Elfriede', 'Blauensteiner', 1);
INSERT INTO BETREUER(ID, NAME) VALUES (2, 'Felix', 'Maier', 1);


INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME) VALUES (1, 'John', 'Mc Affee');
INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME) VALUES (2, 'Frank', 'Buttle');
INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME) VALUES (3, 'Fran', 'Bow');
INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME) VALUES (4, 'Michelle', 'Obama');


