CREATE TABLE PERSON (
ID INTEGER NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR NOT NULL,
LAST_NAME VARCHAR NOT NULL,
DEPARTMENT_ID INT NOT NULL
);

CREATE TABLE ADDRESS(
PERSON_ID INTEGER NOT NULL PRIMARY KEY,
STREET VARCHAR NOT NULL,
CITY VARCHAR NOT NULL,
ZIP VARCHAR NOT NULL
);

CREATE TABLE DEPARTMENT(
ID INTEGER NOT NULL PRIMARY KEY,
NAME VARCHAR NOT NULL
);

CREATE TABLE PROJECT (
ID INTEGER NOT NULL PRIMARY KEY,
NAME VARCHAR NOT NULL
);

-- Junction Table for Many-To-Many Relationship
CREATE TABLE PERSON_PROJECT(
PROJECT_ID INTEGER REFERENCES PROJECT (ID) ON UPDATE CASCADE ON DELETE CASCADE,
PERSON_ID INTEGER REFERENCES PERSON (ID) ON UPDATE CASCADE ON DELETE CASCADE,
PRIMARY KEY(PROJECT_ID, PERSON_ID)
);

ALTER TABLE ADDRESS ADD CONSTRAINT FK_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON;
ALTER TABLE PERSON ADD CONSTRAINT FK_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT; 